# Generated by Django 5.1.1 on 2024-12-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('verified_credentials', models.BooleanField(default=False)),
                ('years_of_experience', models.IntegerField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='instructors/')),
                ('specialties', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
