# Generated by Django 5.1.1 on 2025-01-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_remove_instructor_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
