# Generated by Django 5.1.1 on 2025-01-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='completion_status',
            field=models.BooleanField(default=''),
        ),
    ]
