# Generated by Django 5.1.1 on 2025-01-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_enrollment_completion_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='verified_credentials',
            field=models.ImageField(blank=True, upload_to='credentials/'),
        ),
    ]
