# Generated by Django 5.1.1 on 2025-01-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_instructor_verified_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/instructors'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='verified_credentials',
            field=models.ImageField(blank=True, null=True, upload_to='media/credentials'),
        ),
    ]
