# Generated by Django 5.1.1 on 2025-01-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_instructor_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
