# Generated by Django 5.1.1 on 2025-01-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_enrollment_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='years_of_experience',
            field=models.CharField(default='', max_length=100),
        ),
    ]
